version: '3.8'
services:
  backend:
    image: jonathan31amaral/gymwise-api
    ports:
      - "5099:80"
    restart: always
    networks:
      - GymWise-network

  database:
    image: jonathan31amaral/gymwise-db
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
      POSTGRES_DB: "postgres"
    networks:
      - GymWise-network

networks:
  GymWise-network:
    driver: bridge
